In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sharmajicoder/genn-z-college-admission-dataset")

print("Path to dataset files:", path)

Downloading to C:\Users\Sakshi\.cache\kagglehub\datasets\sharmajicoder\genn-z-college-admission-dataset\1.archive...

100%|██████████| 28.0M/28.0M [00:06<00:00, 4.44MB/s]

Extracting files...

Path to dataset files: C:\Users\Sakshi\.cache\kagglehub\datasets\sharmajicoder\genn-z-college-admission-dataset\versions\1

In [3]:
df= pd.read_csv(f'{path}/genz_college_admission_prediction.csv')
df

,student_id,age,gender,state,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
0,1,22,Male,Ohio,32560,3.20,734,27,91.0,3,3,85,1,4,4.8,1,96.3,90.5,71.7,1
1,2,19,Male,Virginia,39084,4.00,988,26,100.0,0,5,103,1,4,2.7,2,59.9,55.2,93.0,1
2,3,20,Male,Ohio,21615,2.90,1600,28,97.7,2,3,78,2,1,5.4,4,75.2,70.3,70.0,1
3,4,22,Male,Illinois,109493,3.86,1302,28,91.6,4,3,98,0,2,1.8,2,80.7,81.9,98.7,1
4,5,18,Male,Florida,50314,2.50,1342,30,91.8,3,4,35,1,2,5.8,3,63.1,73.7,67.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999996,20,Female,New York,127978,3.98,984,27,94.9,3,6,24,1,2,3.9,2,72.6,76.0,82.0,1
999996,999997,16,Male,Ohio,47661,3.49,940,25,80.6,2,4,206,1,3,6.7,0,88.5,72.9,67.4,1
999997,999998,21,Female,Washington,88044,2.77,1103,16,95.9,0,1,67,0,2,3.7,3,73.1,85.9,77.6,1
999998,999999,17,Female,Virginia,55654,3.71,1208,27,87.8,3,8,24,1,2,2.8,0,72.6,60.9,71.0,1
999999,1000000,18,Male,California,59923,3.41,1241,28,94.0,2,4,184,1,1,1.8,3,70.3,91.7,55.3,1

In [4]:
df.shape

(1000000, 20)

In [5]:
df.size

20000000

In [6]:
df.head(2)

,student_id,age,gender,state,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
0,1,22,Male,Ohio,32560,3.2,734,27,91.0,3,3,85,1,4,4.8,1,96.3,90.5,71.7,1
1,2,19,Male,Virginia,39084,4.0,988,26,100.0,0,5,103,1,4,2.7,2,59.9,55.2,93.0,1

In [7]:
df.isnull().sum()

student_id               0
age                      0
gender                   0
state                    0
family_income            0
high_school_gpa          0
sat_score                0
act_score                0
attendance_rate          0
ap_courses               0
extracurricular_count    0
volunteer_hours          0
leadership_positions     0
coding_projects          0
social_media_hours       0
online_certifications    0
essay_score              0
recommendation_score     0
interview_score          0
admission_status         0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.columns

Index(['student_id', 'age', 'gender', 'state', 'family_income',
       'high_school_gpa', 'sat_score', 'act_score', 'attendance_rate',
       'ap_courses', 'extracurricular_count', 'volunteer_hours',
       'leadership_positions', 'coding_projects', 'social_media_hours',
       'online_certifications', 'essay_score', 'recommendation_score',
       'interview_score', 'admission_status'],
      dtype='str')

In [10]:
df=df.drop(columns=['student_id'])

In [11]:
df.head(1)

,age,gender,state,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
0,22,Male,Ohio,32560,3.2,734,27,91.0,3,3,85,1,4,4.8,1,96.3,90.5,71.7,1

In [12]:
obj =LabelEncoder()

df['gender'] =obj.fit_transform(df['gender'])
df['state'] =obj.fit_transform(df['state'])

In [13]:
df.dtypes

age                        int64
gender                     int64
state                      int64
family_income              int64
high_school_gpa          float64
sat_score                  int64
act_score                  int64
attendance_rate          float64
ap_courses                 int64
extracurricular_count      int64
volunteer_hours            int64
leadership_positions       int64
coding_projects            int64
social_media_hours       float64
online_certifications      int64
essay_score              float64
recommendation_score     float64
interview_score          float64
admission_status           int64
dtype: object

In [14]:
df.columns

Index(['age', 'gender', 'state', 'family_income', 'high_school_gpa',
       'sat_score', 'act_score', 'attendance_rate', 'ap_courses',
       'extracurricular_count', 'volunteer_hours', 'leadership_positions',
       'coding_projects', 'social_media_hours', 'online_certifications',
       'essay_score', 'recommendation_score', 'interview_score',
       'admission_status'],
      dtype='str')

In [15]:
x=df[['age', 'gender', 'state', 'family_income', 'high_school_gpa',
       'sat_score', 'act_score', 'attendance_rate', 'ap_courses',
       'extracurricular_count', 'volunteer_hours', 'leadership_positions',
       'coding_projects', 'social_media_hours', 'online_certifications',
       'essay_score', 'recommendation_score', 'interview_score']]
y=df['admission_status']

In [16]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

In [18]:
model=AdaBoostClassifier()
model.fit(x_train, y_train)

AdaBoostClassifier()

In [19]:
predictions = model.predict(x_test)
predictions

array([1, 1, 1, ..., 1, 1, 1], shape=(200000,))

In [20]:
Score= classification_report(y_test, predictions)
print(Score)

              precision    recall  f1-score   support

           0       0.59      0.29      0.39     23708
           1       0.91      0.97      0.94    176292

    accuracy                           0.89    200000
   macro avg       0.75      0.63      0.67    200000
weighted avg       0.87      0.89      0.88    200000

In [21]:
import pickle
pickle.dump(model, open('adaboost.pkl','wb'))
print('PKL File Created Successfully')

PKL File Created Successfully